---
title: "style model"
output:
  md_document:
    variant: markdown_github
  html_document:
   toc: true
   theme: united
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
data <- read.csv("styleTest.csv")
data$count <- (data$id %% 10) * 200
data$type <- data$id %/% 10
means <- aggregate(data, list(data$id), FUN=mean)
stdevs <- aggregate(data, list(data$id), FUN=sd)
means$HDPpPCFBPsd <- stdevs$HTMLDocumentParser..processParsedChunkFromBackgroundParser
means$DuSsd <- stdevs$Document..updateStyle
means$FVpLsd <- stdevs$FrameView..performLayout

data$typeName <- ifelse(data$type == 0, ".a .c", ifelse(data$type == 1, ".b ~ .c", ".c"))
means$typeName <- ifelse(means$type == 0, ".a .c", ifelse(means$type == 1, ".b ~ .c", ".c"))

library(ggplot2)

```

Comparison of single selectors ".a .c", ".b ~ .c", and ".c" matching against variable number of element subtrees:

```
<div class='a'>
  <div class='b'>
  </div>
  <div class='c'>
  </div>
</div>
```

Three properties are set in a single rule:

```
%SEL {
  background-color: red;
  width: 100px;
  height: 100px;
}
```

Graphs contain `r length(data$id)` samples.

```{r, echo=FALSE, warning=FALSE, message=FALSE}
ggplot(means, aes(x=count, y=HTMLDocumentParser..processParsedChunkFromBackgroundParser, group=type, colour=typeName)) + geom_line(aes(y=HTMLDocumentParser..processParsedChunkFromBackgroundParser-HDPpPCFBPsd), linetype=2) +  geom_line(aes(y=HTMLDocumentParser..processParsedChunkFromBackgroundParser+HDPpPCFBPsd), linetype=2) + geom_line(size=1.1)
ggplot(means, aes(x=count, y=Document..updateStyle, group=type, colour=typeName)) + geom_line(aes(y=Document..updateStyle-DuSsd), linetype=2) + geom_line(aes(y=Document..updateStyle+DuSsd), linetype=2) + geom_line(size=1.1)
ggplot(means, aes(x=count, y=FrameView..performLayout, group=type, colour=typeName)) + geom_line(aes(y=FrameView..performLayout-FVpLsd), linetype=2) +geom_line(aes(y=FrameView..performLayout+FVpLsd), linetype=2) + geom_line(size=1.1)
```
